T=int(input("Enter time period:"))
R=float(input("Enter annual interest rate:"))
P=float(input("Enter principal amount:"))
n=int(input("Enter number of months:"))
A = P*(1+(R/n)**(n*T))
print("the value is:", A)